version: 2
jobs:
  # build using ubuntu LTS
  "build/ubuntu-bionic":
    docker:
      - image: ubuntu:bionic
    steps:
      - checkout
      - run:
          name: update base image
          command: apt update -y
      - run:
          name: install dependencies
          command: apt install libssl-dev libyaml-dev libncurses-dev libc-ares-dev libprotobuf-dev protobuf-compiler libjq-dev libyaml-cpp-dev libgrpc++-dev protobuf-compiler-grpc rpm linux-headers-$(uname -r) libelf-dev cmake build-essential libcurl4-openssl-dev -y
      - run:
          name: prepare project
          command: |
            mkdir build
            pushd build
            cmake ..
            popd
      - run:
          name: build
          command: |
            pushd build
            make -j all
            popd
      - run:
          name: run unit tests
          command: |
            pushd build
            make tests
            popd
  # build using our own builder base image using centos 7
  "build/centos7":
    docker:
      - image: falcosecurity/falco-builder:dynamic-builds # todo(fntlnz): replace this with the actual image once PR #968 is merged
    steps:
      - checkout:
          path: /source/falco
      - run:
          name: prepare project
          command: /usr/bin/entrypoint cmake
      - run:
          name: prepare project
          command: /usr/bin/entrypoint all
      - persist_to_workspace:
          root: /
          paths:
            - build
  # execute integration tests based on the build results coming from the "build/centos7" job
  "tests/integration":
    docker:
      - image: falcosecurity/falco-tester:latest
    steps:
      - checkout:
          path: /source/falco
      - attach_workspace:
          at: /build
      - run:
          name: execute integration tests
          command: |
            ls -la /
            ls -la /build
workflows:
  version: 2
  build_and_test:
    jobs:
      - "build/ubuntu-bionic"
      - "build/centos7"
      - "tests/integration":
          requires:
            - "build/centos7"
